# Generated by Django 2.2.24 on 2021-08-10 17:10

import cms.utils.i18n
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='FormContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('en', 'English')], default=cms.utils.i18n.get_current_language, max_length=10)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_formbuilder.Form')),
            ],
            options={
                'verbose_name': 'form content',
                'verbose_name_plural': 'form contents',
            },
        ),
    ]
